# These are supported funding model platforms

github: github.com/underfix
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective username
paypal: # Replace with a single Ko-fi username
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
Bitcoin Wallet: # 3u0ejirf8f94hechj222
